---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: elasticsearch
    run_list: "recipe[odi-elasticsearch-wrapper]"
    attributes:
    data_bags_path: test/data_bags/elasticsearch
